# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f18a9d223c88fbc71d8d1f13e7935709a45d8a81e6d4e997ecc29fc9d4b479a60a126bd50766e1170773428b4839d3680219af9e53cec815541a51b58897a92

test:
  secret_key_base: 6a9d33c040ffe703af65ab1761aa7fde0c847534dbbc290a3fd7bc86e55e4c9b660780278aa354dde6a5868c23ceda2ecae12cd607aa53766598f1c2e5d96bca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
